name: Deploy to GitHub Pages
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: enriikke/nextjs-github-pages@v1.1.1
      with:
        GH_PAGES_BRANCH: gh-pages
        BUILD_SCRIPT: npm run build
        EXPORT_DIR: ./out
